apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ticketsystem
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch-data
  name: elasticsearch-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
