apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ticketsystem
  creationTimestamp: null
  labels:
    io.kompose.service: opt-otobo
  name: opt-otobo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
